modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="aarium"
version="1.0.0"
displayName="Aarium"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="nino_, MCreator"

[[dependencies.aarium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




